# Generated by Django 2.0.6 on 2018-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('archivo', models.FileField(upload_to='documents')),
            ],
        ),
    ]
