# Generated by Django 2.0.7 on 2018-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrPCsMunicipioRW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pc',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pc',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pc',
            name='usuario',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
