# Generated by Django 2.0.6 on 2018-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrPCsMunicipioRW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
    ]
